/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UII;

import dao.*;
import java.awt.CardLayout;
import entity.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Outer = new javax.swing.JPanel();
        DangNhap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_dangnhap_taikhoan = new javax.swing.JTextField();
        btn_dangnhap_dangnhap = new javax.swing.JButton();
        txt_dangnhap_matkhau = new javax.swing.JPasswordField();
        ChucNang = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        cardlayout_QuanLyNhanVien = new javax.swing.JPanel();
        QuanLyNhanVien = new javax.swing.JPanel();
        btn_qlnv_trangchu = new javax.swing.JButton();
        btn_qlnv_suattnv = new javax.swing.JButton();
        btn_qlnv_dangkytknv = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_qlnv_tennv = new javax.swing.JTextField();
        txt_qlnv_idtk = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_qlnv_mk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_qlnv_sdt = new javax.swing.JTextField();
        scroll_qlnv_bang = new javax.swing.JScrollPane();
        table_qlnv_bang = new javax.swing.JTable();
        cardlayout_QuanLyHoaDon = new javax.swing.JPanel();
        QuanLyHoaDon = new javax.swing.JPanel();
        btn_qlhd_trangchu = new javax.swing.JButton();
        btn_qlhd_thongke = new javax.swing.JButton();
        scroll_qlhd_bang = new javax.swing.JScrollPane();
        table_qlhd_bang = new javax.swing.JTable();
        ThongKe = new javax.swing.JPanel();
        btn_thongke_qlhd = new javax.swing.JButton();
        cardlayout_QuanLyKhachHang = new javax.swing.JPanel();
        QuanLyKhachHang = new javax.swing.JPanel();
        btn_qlkh_trangchu = new javax.swing.JButton();
        btn_qlkh_taokh = new javax.swing.JButton();
        btn_qlkh_suatt = new javax.swing.JButton();
        btn_qlkh_timkhtheosdt = new javax.swing.JButton();
        txt_qlkh_tim = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_qlkh_tenkh = new javax.swing.JTextField();
        txt_qlkh_sdt = new javax.swing.JTextField();
        txt_qlkh_makh = new javax.swing.JTextField();
        scroll_qlkh_bang = new javax.swing.JScrollPane();
        table_qlkh_bang = new javax.swing.JTable();
        cardlayout_QuanLyBan = new javax.swing.JPanel();
        QuanLyBan = new javax.swing.JPanel();
        btn_qlban_trangchu = new javax.swing.JButton();
        btn_qlban_suaban = new javax.swing.JButton();
        btn_qlban_themban = new javax.swing.JButton();
        btn_qlban_xoaban = new javax.swing.JButton();
        scroll_qlban_bang = new javax.swing.JScrollPane();
        table_qlban_bang = new javax.swing.JTable();
        cardlayout_QuanLyDatBan = new javax.swing.JPanel();
        cardlayout_QuanLyDatMon = new javax.swing.JPanel();
        QuanLyDatMon = new javax.swing.JPanel();
        btn_qldm_qldb = new javax.swing.JButton();
        btn_qldm_datmon = new javax.swing.JButton();
        btn_qldm_xoamon = new javax.swing.JButton();
        scroll_qldm_bang = new javax.swing.JScrollPane();
        table_qldm_bang = new javax.swing.JTable();
        DatMon = new javax.swing.JPanel();
        btn_datmon_qldm = new javax.swing.JButton();
        XoaMon = new javax.swing.JPanel();
        btn_xoamon_qldm = new javax.swing.JButton();
        SuaThongTinDatBan = new javax.swing.JPanel();
        btn_suattban_qldb = new javax.swing.JButton();
        DatBan = new javax.swing.JPanel();
        btn_db_qldb = new javax.swing.JButton();
        QuanLyDatBan = new javax.swing.JPanel();
        btn_qldb_trangchu = new javax.swing.JButton();
        btn_qldb_qldatmon = new javax.swing.JButton();
        btn_qldb_timkiem = new javax.swing.JButton();
        btn_qldb_laphoadon = new javax.swing.JButton();
        btn_qldb_suattdatban = new javax.swing.JButton();
        btn_qldb_huydatban = new javax.swing.JButton();
        btn_qldb_datban = new javax.swing.JButton();
        scroll_qldb_bang = new javax.swing.JScrollPane();
        table_qldb_bang = new javax.swing.JTable();
        cbo_qldb_item = new javax.swing.JComboBox<>();
        Menu = new javax.swing.JPanel();
        scroll_menu = new javax.swing.JScrollPane();
        table_menu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setSize(new java.awt.Dimension(1100, 600));

        Outer.setBackground(new java.awt.Color(0, 255, 255));
        Outer.setMaximumSize(new java.awt.Dimension(1100, 600));
        Outer.setMinimumSize(new java.awt.Dimension(1100, 600));
        Outer.setName(""); // NOI18N
        Outer.setPreferredSize(new java.awt.Dimension(1100, 600));
        Outer.setLayout(new java.awt.CardLayout());

        DangNhap.setBackground(new java.awt.Color(255, 255, 255));
        DangNhap.setMaximumSize(new java.awt.Dimension(1100, 600));
        DangNhap.setMinimumSize(new java.awt.Dimension(1100, 600));
        DangNhap.setPreferredSize(new java.awt.Dimension(1100, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Tài Khoản :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mật Khẩu :");

        btn_dangnhap_dangnhap.setText("Đăng Nhập");
        btn_dangnhap_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhap_dangnhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DangNhapLayout = new javax.swing.GroupLayout(DangNhap);
        DangNhap.setLayout(DangNhapLayout);
        DangNhapLayout.setHorizontalGroup(
            DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapLayout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_dangnhap_dangnhap)
                    .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_dangnhap_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_dangnhap_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangNhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        DangNhapLayout.setVerticalGroup(
            DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_dangnhap_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dangnhap_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_dangnhap_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        Outer.add(DangNhap, "dangnhap");

        ChucNang.setBackground(new java.awt.Color(153, 255, 204));
        ChucNang.setMaximumSize(new java.awt.Dimension(1100, 600));
        ChucNang.setMinimumSize(new java.awt.Dimension(1100, 600));
        ChucNang.setPreferredSize(new java.awt.Dimension(1100, 600));
        ChucNang.setVerifyInputWhenFocusTarget(false);

        MainPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        MainPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        MainPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        MainPanel.setLayout(new java.awt.CardLayout());

        cardlayout_QuanLyNhanVien.setLayout(new java.awt.CardLayout());

        QuanLyNhanVien.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyNhanVien.setMinimumSize(new java.awt.Dimension(900, 600));
        QuanLyNhanVien.setPreferredSize(new java.awt.Dimension(900, 600));

        btn_qlnv_trangchu.setText("Trang Chủ");
        btn_qlnv_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnv_trangchuActionPerformed(evt);
            }
        });

        btn_qlnv_suattnv.setText("Sửa thông tin");
        btn_qlnv_suattnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnv_suattnvActionPerformed(evt);
            }
        });

        btn_qlnv_dangkytknv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_qlnv_dangkytknv.setText("Tạo Tài Khoản Nhân Viên");
        btn_qlnv_dangkytknv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnv_dangkytknvActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("ID tài khoản:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mật khẩu :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Số điện thoại:");

        table_qlnv_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên nhân viên", "ID tài khoản", "Mật khẩu", "Số điện thoại"
            }
        ));
        scroll_qlnv_bang.setViewportView(table_qlnv_bang);

        javax.swing.GroupLayout QuanLyNhanVienLayout = new javax.swing.GroupLayout(QuanLyNhanVien);
        QuanLyNhanVien.setLayout(QuanLyNhanVienLayout);
        QuanLyNhanVienLayout.setHorizontalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_qlnv_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_qlnv_suattnv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_qlnv_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_qlnv_dangkytknv)
                        .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                            .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(39, 39, 39)
                            .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_qlnv_tennv)
                                .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                                    .addComponent(txt_qlnv_idtk, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_qlnv_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_qlnv_sdt)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyNhanVienLayout.setVerticalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qlnv_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_qlnv_idtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_qlnv_mk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qlnv_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btn_qlnv_dangkytknv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                        .addComponent(btn_qlnv_trangchu)
                        .addGap(27, 27, 27)
                        .addComponent(btn_qlnv_suattnv))
                    .addComponent(scroll_qlnv_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        cardlayout_QuanLyNhanVien.add(QuanLyNhanVien, "qlnv");

        MainPanel.add(cardlayout_QuanLyNhanVien, "qlynhanvien");

        cardlayout_QuanLyHoaDon.setLayout(new java.awt.CardLayout());

        QuanLyHoaDon.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyHoaDon.setMinimumSize(new java.awt.Dimension(900, 600));

        btn_qlhd_trangchu.setText("Trang Chủ");
        btn_qlhd_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlhd_trangchuActionPerformed(evt);
            }
        });

        btn_qlhd_thongke.setText("Thống kê");
        btn_qlhd_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlhd_thongkeActionPerformed(evt);
            }
        });

        table_qlhd_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_qlhd_bang.setViewportView(table_qlhd_bang);

        javax.swing.GroupLayout QuanLyHoaDonLayout = new javax.swing.GroupLayout(QuanLyHoaDon);
        QuanLyHoaDon.setLayout(QuanLyHoaDonLayout);
        QuanLyHoaDonLayout.setHorizontalGroup(
            QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_qlhd_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlhd_trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(scroll_qlhd_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyHoaDonLayout.setVerticalGroup(
            QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyHoaDonLayout.createSequentialGroup()
                .addGroup(QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyHoaDonLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btn_qlhd_trangchu)
                        .addGap(27, 27, 27)
                        .addComponent(btn_qlhd_thongke))
                    .addGroup(QuanLyHoaDonLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(scroll_qlhd_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyHoaDon.add(QuanLyHoaDon, "qlhd");

        btn_thongke_qlhd.setText("Quay Lại");
        btn_thongke_qlhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongke_qlhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_thongke_qlhd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_thongke_qlhd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyHoaDon.add(ThongKe, "thongke");

        MainPanel.add(cardlayout_QuanLyHoaDon, "qlyhoadon");

        cardlayout_QuanLyKhachHang.setLayout(new java.awt.CardLayout());

        QuanLyKhachHang.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyKhachHang.setMinimumSize(new java.awt.Dimension(900, 600));
        QuanLyKhachHang.setPreferredSize(new java.awt.Dimension(900, 600));

        btn_qlkh_trangchu.setText("Trang Chủ");
        btn_qlkh_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkh_trangchuActionPerformed(evt);
            }
        });

        btn_qlkh_taokh.setText("Tạo khách hàng");
        btn_qlkh_taokh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkh_taokhActionPerformed(evt);
            }
        });

        btn_qlkh_suatt.setText("Sửa thông tin");
        btn_qlkh_suatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkh_suattActionPerformed(evt);
            }
        });

        btn_qlkh_timkhtheosdt.setText("Tìm:");
        btn_qlkh_timkhtheosdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkh_timkhtheosdtActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Tên khách hàng:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Số điện thoại:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Mã khách hàng:");

        table_qlkh_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_qlkh_bang.setViewportView(table_qlkh_bang);

        javax.swing.GroupLayout QuanLyKhachHangLayout = new javax.swing.GroupLayout(QuanLyKhachHang);
        QuanLyKhachHang.setLayout(QuanLyKhachHangLayout);
        QuanLyKhachHangLayout.setHorizontalGroup(
            QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_qlkh_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_qlkh_suatt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_qlkh_makh)
                            .addComponent(txt_qlkh_sdt)
                            .addComponent(txt_qlkh_tenkh))
                        .addGap(148, 148, 148))
                    .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                        .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scroll_qlkh_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                                .addComponent(btn_qlkh_timkhtheosdt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_qlkh_tim)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_qlkh_taokh)
                .addGap(314, 314, 314))
        );
        QuanLyKhachHangLayout.setVerticalGroup(
            QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_qlkh_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_qlkh_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_qlkh_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btn_qlkh_taokh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                        .addComponent(btn_qlkh_trangchu)
                        .addGap(26, 26, 26)
                        .addComponent(btn_qlkh_suatt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scroll_qlkh_bang, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qlkh_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_qlkh_timkhtheosdt))
                .addGap(15, 15, 15))
        );

        cardlayout_QuanLyKhachHang.add(QuanLyKhachHang, "qlkh");

        MainPanel.add(cardlayout_QuanLyKhachHang, "qlykhachhang");

        cardlayout_QuanLyBan.setLayout(new java.awt.CardLayout());

        QuanLyBan.setBackground(new java.awt.Color(204, 204, 204));

        btn_qlban_trangchu.setText("Trang Chủ");
        btn_qlban_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_trangchuActionPerformed(evt);
            }
        });

        btn_qlban_suaban.setText("Sửa bàn");
        btn_qlban_suaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_suabanActionPerformed(evt);
            }
        });

        btn_qlban_themban.setText("Thêm bàn");
        btn_qlban_themban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_thembanActionPerformed(evt);
            }
        });

        btn_qlban_xoaban.setText("Xóa bàn");
        btn_qlban_xoaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_xoabanActionPerformed(evt);
            }
        });

        table_qlban_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Bàn", "Mã Khu", "Trạng Thái", "Đơn Giá"
            }
        ));
        scroll_qlban_bang.setViewportView(table_qlban_bang);

        javax.swing.GroupLayout QuanLyBanLayout = new javax.swing.GroupLayout(QuanLyBan);
        QuanLyBan.setLayout(QuanLyBanLayout);
        QuanLyBanLayout.setHorizontalGroup(
            QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_qlban_themban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlban_suaban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlban_trangchu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlban_xoaban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(scroll_qlban_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyBanLayout.setVerticalGroup(
            QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyBanLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyBanLayout.createSequentialGroup()
                        .addComponent(btn_qlban_trangchu)
                        .addGap(32, 32, 32)
                        .addComponent(btn_qlban_suaban)
                        .addGap(35, 35, 35)
                        .addComponent(btn_qlban_themban)
                        .addGap(33, 33, 33)
                        .addComponent(btn_qlban_xoaban))
                    .addComponent(scroll_qlban_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyBan.add(QuanLyBan, "qlban");

        MainPanel.add(cardlayout_QuanLyBan, "qlyban");

        cardlayout_QuanLyDatBan.setLayout(new java.awt.CardLayout());

        cardlayout_QuanLyDatMon.setPreferredSize(new java.awt.Dimension(600, 400));
        cardlayout_QuanLyDatMon.setLayout(new java.awt.CardLayout());

        QuanLyDatMon.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyDatMon.setMinimumSize(new java.awt.Dimension(900, 600));
        QuanLyDatMon.setPreferredSize(new java.awt.Dimension(900, 600));

        btn_qldm_qldb.setText("Quay Lại");
        btn_qldm_qldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldm_qldbActionPerformed(evt);
            }
        });

        btn_qldm_datmon.setText("Đặt món");
        btn_qldm_datmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldm_datmonActionPerformed(evt);
            }
        });

        btn_qldm_xoamon.setText("Xóa món");
        btn_qldm_xoamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldm_xoamonActionPerformed(evt);
            }
        });

        table_qldm_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_qldm_bang.setViewportView(table_qldm_bang);

        javax.swing.GroupLayout QuanLyDatMonLayout = new javax.swing.GroupLayout(QuanLyDatMon);
        QuanLyDatMon.setLayout(QuanLyDatMonLayout);
        QuanLyDatMonLayout.setHorizontalGroup(
            QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                        .addComponent(scroll_qldm_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_qldm_datmon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_qldm_xoamon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                        .addComponent(btn_qldm_qldb)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QuanLyDatMonLayout.setVerticalGroup(
            QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_qldm_qldb)
                .addGap(18, 18, 18)
                .addGroup(QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_qldm_datmon)
                            .addComponent(btn_qldm_xoamon)))
                    .addComponent(scroll_qldm_bang))
                .addContainerGap())
        );

        cardlayout_QuanLyDatMon.add(QuanLyDatMon, "qldatmon");

        DatMon.setPreferredSize(new java.awt.Dimension(600, 400));

        btn_datmon_qldm.setText("Quay Lại");
        btn_datmon_qldm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datmon_qldmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatMonLayout = new javax.swing.GroupLayout(DatMon);
        DatMon.setLayout(DatMonLayout);
        DatMonLayout.setHorizontalGroup(
            DatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_datmon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatMonLayout.setVerticalGroup(
            DatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_datmon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatMon.add(DatMon, "datmon");

        XoaMon.setPreferredSize(new java.awt.Dimension(600, 400));

        btn_xoamon_qldm.setText("Quay Lại");
        btn_xoamon_qldm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoamon_qldmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XoaMonLayout = new javax.swing.GroupLayout(XoaMon);
        XoaMon.setLayout(XoaMonLayout);
        XoaMonLayout.setHorizontalGroup(
            XoaMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XoaMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_xoamon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        XoaMonLayout.setVerticalGroup(
            XoaMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XoaMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_xoamon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatMon.add(XoaMon, "xoamon");

        cardlayout_QuanLyDatBan.add(cardlayout_QuanLyDatMon, "qldm");

        btn_suattban_qldb.setText("Quay Lại");
        btn_suattban_qldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suattban_qldbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuaThongTinDatBanLayout = new javax.swing.GroupLayout(SuaThongTinDatBan);
        SuaThongTinDatBan.setLayout(SuaThongTinDatBanLayout);
        SuaThongTinDatBanLayout.setHorizontalGroup(
            SuaThongTinDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuaThongTinDatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_suattban_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SuaThongTinDatBanLayout.setVerticalGroup(
            SuaThongTinDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuaThongTinDatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_suattban_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatBan.add(SuaThongTinDatBan, "suattdatban");

        btn_db_qldb.setText("Quay Lại");
        btn_db_qldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_db_qldbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatBanLayout = new javax.swing.GroupLayout(DatBan);
        DatBan.setLayout(DatBanLayout);
        DatBanLayout.setHorizontalGroup(
            DatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_db_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatBanLayout.setVerticalGroup(
            DatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_db_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatBan.add(DatBan, "datban");

        QuanLyDatBan.setPreferredSize(new java.awt.Dimension(1200, 900));

        btn_qldb_trangchu.setText("Trang Chủ");
        btn_qldb_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_trangchuActionPerformed(evt);
            }
        });

        btn_qldb_qldatmon.setText("Quản lý đặt món");
        btn_qldb_qldatmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_qldatmonActionPerformed(evt);
            }
        });

        btn_qldb_timkiem.setText("Tìm kiếm");
        btn_qldb_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_timkiemActionPerformed(evt);
            }
        });

        btn_qldb_laphoadon.setText("Lập hóa đơn");
        btn_qldb_laphoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_laphoadonActionPerformed(evt);
            }
        });

        btn_qldb_suattdatban.setText("Sửa thông tin đặt bàn");
        btn_qldb_suattdatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_suattdatbanActionPerformed(evt);
            }
        });

        btn_qldb_huydatban.setText("Hủy đặt bàn");
        btn_qldb_huydatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_huydatbanActionPerformed(evt);
            }
        });

        btn_qldb_datban.setText("Đặt bàn");
        btn_qldb_datban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_datbanActionPerformed(evt);
            }
        });

        table_qldb_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_qldb_bang.setViewportView(table_qldb_bang);

        cbo_qldb_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_qldb_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_qldb_itemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyDatBanLayout = new javax.swing.GroupLayout(QuanLyDatBan);
        QuanLyDatBan.setLayout(QuanLyDatBanLayout);
        QuanLyDatBanLayout.setHorizontalGroup(
            QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_qldb_datban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_qldb_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_qldatmon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_laphoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_suattdatban, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_huydatban, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                        .addComponent(btn_qldb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cbo_qldb_item, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scroll_qldb_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyDatBanLayout.setVerticalGroup(
            QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_qldb_timkiem)
                    .addComponent(cbo_qldb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                        .addComponent(btn_qldb_trangchu)
                        .addGap(18, 18, 18)
                        .addComponent(btn_qldb_qldatmon)
                        .addGap(27, 27, 27)
                        .addComponent(btn_qldb_laphoadon)
                        .addGap(30, 30, 30)
                        .addComponent(btn_qldb_suattdatban)
                        .addGap(26, 26, 26)
                        .addComponent(btn_qldb_huydatban)
                        .addGap(28, 28, 28)
                        .addComponent(btn_qldb_datban))
                    .addComponent(scroll_qldb_bang, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatBan.add(QuanLyDatBan, "qldb");

        MainPanel.add(cardlayout_QuanLyDatBan, "qlydatban");

        Menu.setBackground(new java.awt.Color(0, 255, 255));
        Menu.setMaximumSize(new java.awt.Dimension(200, 600));
        Menu.setMinimumSize(new java.awt.Dimension(200, 600));
        Menu.setName(""); // NOI18N
        Menu.setPreferredSize(new java.awt.Dimension(200, 600));

        table_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        scroll_menu.setViewportView(table_menu);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addComponent(scroll_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout ChucNangLayout = new javax.swing.GroupLayout(ChucNang);
        ChucNang.setLayout(ChucNangLayout);
        ChucNangLayout.setHorizontalGroup(
            ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChucNangLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChucNangLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        ChucNangLayout.setVerticalGroup(
            ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChucNangLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ChucNangLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        Outer.add(ChucNang, "chucnang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Outer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Outer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_qlnv_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnv_trangchuActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "trangchu");    }//GEN-LAST:event_btn_qlnv_trangchuActionPerformed

    private void btn_qlnv_suattnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnv_suattnvActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyNhanVien.getLayout();
        card.show(cardlayout_QuanLyNhanVien, "suattnv");
    }//GEN-LAST:event_btn_qlnv_suattnvActionPerformed

    private void btn_qlhd_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlhd_trangchuActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "trangchu");
    }//GEN-LAST:event_btn_qlhd_trangchuActionPerformed

    private void btn_qlhd_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlhd_thongkeActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyHoaDon.getLayout();
        card.show(cardlayout_QuanLyHoaDon, "thongke");
    }//GEN-LAST:event_btn_qlhd_thongkeActionPerformed

    private void btn_thongke_qlhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongke_qlhdActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyHoaDon.getLayout();
        card.show(cardlayout_QuanLyHoaDon, "qlhd");
    }//GEN-LAST:event_btn_thongke_qlhdActionPerformed

    private void btn_qlkh_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkh_trangchuActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "trangchu");
    }//GEN-LAST:event_btn_qlkh_trangchuActionPerformed

    private void btn_qlkh_taokhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkh_taokhActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyKhachHang.getLayout();
        card.show(cardlayout_QuanLyKhachHang, "taokh");
    }//GEN-LAST:event_btn_qlkh_taokhActionPerformed

    private void btn_qlkh_suattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkh_suattActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyKhachHang.getLayout();
        card.show(cardlayout_QuanLyKhachHang, "suatt");
    }//GEN-LAST:event_btn_qlkh_suattActionPerformed

    private void btn_qlkh_timkhtheosdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkh_timkhtheosdtActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyKhachHang.getLayout();
        card.show(cardlayout_QuanLyKhachHang, "timkhtheosdt");
    }//GEN-LAST:event_btn_qlkh_timkhtheosdtActionPerformed

    private void btn_qlban_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_trangchuActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "trangchu");
    }//GEN-LAST:event_btn_qlban_trangchuActionPerformed

    private void btn_qlban_suabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_suabanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyBan.getLayout();
        card.show(cardlayout_QuanLyBan, "suaban");
    }//GEN-LAST:event_btn_qlban_suabanActionPerformed

    private void btn_qlban_thembanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_thembanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyBan.getLayout();
        card.show(cardlayout_QuanLyBan, "themban");
    }//GEN-LAST:event_btn_qlban_thembanActionPerformed

    private void btn_qlban_xoabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_xoabanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyBan.getLayout();
        card.show(cardlayout_QuanLyBan, "xoaban");
    }//GEN-LAST:event_btn_qlban_xoabanActionPerformed

    private void btn_qldb_qldatmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_qldatmonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldm");
    }//GEN-LAST:event_btn_qldb_qldatmonActionPerformed

    private void btn_qldb_laphoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_laphoadonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "laphoadon");
    }//GEN-LAST:event_btn_qldb_laphoadonActionPerformed

    private void btn_qldb_suattdatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_suattdatbanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "suattdatban");
    }//GEN-LAST:event_btn_qldb_suattdatbanActionPerformed

    private void btn_qldb_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_trangchuActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "trangchu");
    }//GEN-LAST:event_btn_qldb_trangchuActionPerformed

    private void btn_qldb_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_timkiemActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "timkiem");
    }//GEN-LAST:event_btn_qldb_timkiemActionPerformed

    private void btn_qldb_huydatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_huydatbanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "huydatban");
    }//GEN-LAST:event_btn_qldb_huydatbanActionPerformed

    private void btn_qldb_datbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_datbanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "datban");
    }//GEN-LAST:event_btn_qldb_datbanActionPerformed

    private void btn_qldm_qldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldm_qldbActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldb");
    }//GEN-LAST:event_btn_qldm_qldbActionPerformed

    private void btn_qldm_datmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldm_datmonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "datmon");
    }//GEN-LAST:event_btn_qldm_datmonActionPerformed

    private void btn_qldm_xoamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldm_xoamonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "xoamon");
    }//GEN-LAST:event_btn_qldm_xoamonActionPerformed

    private void btn_datmon_qldmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datmon_qldmActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "qldatmon");
    }//GEN-LAST:event_btn_datmon_qldmActionPerformed

    private void btn_xoamon_qldmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoamon_qldmActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "qldatmon");
    }//GEN-LAST:event_btn_xoamon_qldmActionPerformed

    private void btn_suattban_qldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suattban_qldbActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldb");
    }//GEN-LAST:event_btn_suattban_qldbActionPerformed

    private void btn_db_qldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_db_qldbActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldb");
    }//GEN-LAST:event_btn_db_qldbActionPerformed

    private void btn_dangnhap_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhap_dangnhapActionPerformed
        // TODO add your handling code here:
        
        checkLoginCredentials();
    }//GEN-LAST:event_btn_dangnhap_dangnhapActionPerformed

    private void cbo_qldb_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_qldb_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_qldb_itemActionPerformed

    private void btn_qlnv_dangkytknvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnv_dangkytknvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_qlnv_dangkytknvActionPerformed

    /**
     * @param args the command line arguments
     */
    private void checkLoginCredentials() {
    String username = txt_dangnhap_taikhoan.getText().trim();
    String password = txt_dangnhap_matkhau.getText().trim();

    // Kiểm tra tài khoản có đúng định dạng không (6 số)
    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập tài khoản!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        txt_dangnhap_taikhoan.requestFocus();
        return;
    }

    // Kiểm tra mật khẩu không được để trống
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        txt_dangnhap_matkhau.requestFocus();
        return;
    }
    TK_NhanVien_DAO tknv_dao = new TK_NhanVien_DAO();
    List<TK_NhanVien> tknv_list = tknv_dao.getAllTK_NhanViens();
    boolean check = false;
    for(TK_NhanVien tknv : tknv_list){
        if(tknv.getNv().getMaNV().equals(username)&&tknv.getMatKhauTK().equals(password)){
            check = true;
            break;
        }
    }
    
    // Kiểm tra thông tin đăng nhập (thay bằng dữ liệu từ CSDL nếu cần)
    if (check) {
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        CardLayout card = (CardLayout)Outer.getLayout();
        card.show(Outer, "chucnang");
        // Mở giao diện trang chủ
        
    } else {
        JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChucNang;
    private javax.swing.JPanel DangNhap;
    private javax.swing.JPanel DatBan;
    private javax.swing.JPanel DatMon;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Outer;
    private javax.swing.JPanel QuanLyBan;
    private javax.swing.JPanel QuanLyDatBan;
    private javax.swing.JPanel QuanLyDatMon;
    private javax.swing.JPanel QuanLyHoaDon;
    private javax.swing.JPanel QuanLyKhachHang;
    private javax.swing.JPanel QuanLyNhanVien;
    private javax.swing.JPanel SuaThongTinDatBan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel XoaMon;
    private javax.swing.JButton btn_dangnhap_dangnhap;
    private javax.swing.JButton btn_datmon_qldm;
    private javax.swing.JButton btn_db_qldb;
    private javax.swing.JButton btn_qlban_suaban;
    private javax.swing.JButton btn_qlban_themban;
    private javax.swing.JButton btn_qlban_trangchu;
    private javax.swing.JButton btn_qlban_xoaban;
    private javax.swing.JButton btn_qldb_datban;
    private javax.swing.JButton btn_qldb_huydatban;
    private javax.swing.JButton btn_qldb_laphoadon;
    private javax.swing.JButton btn_qldb_qldatmon;
    private javax.swing.JButton btn_qldb_suattdatban;
    private javax.swing.JButton btn_qldb_timkiem;
    private javax.swing.JButton btn_qldb_trangchu;
    private javax.swing.JButton btn_qldm_datmon;
    private javax.swing.JButton btn_qldm_qldb;
    private javax.swing.JButton btn_qldm_xoamon;
    private javax.swing.JButton btn_qlhd_thongke;
    private javax.swing.JButton btn_qlhd_trangchu;
    private javax.swing.JButton btn_qlkh_suatt;
    private javax.swing.JButton btn_qlkh_taokh;
    private javax.swing.JButton btn_qlkh_timkhtheosdt;
    private javax.swing.JButton btn_qlkh_trangchu;
    private javax.swing.JButton btn_qlnv_dangkytknv;
    private javax.swing.JButton btn_qlnv_suattnv;
    private javax.swing.JButton btn_qlnv_trangchu;
    private javax.swing.JButton btn_suattban_qldb;
    private javax.swing.JButton btn_thongke_qlhd;
    private javax.swing.JButton btn_xoamon_qldm;
    private javax.swing.JPanel cardlayout_QuanLyBan;
    private javax.swing.JPanel cardlayout_QuanLyDatBan;
    private javax.swing.JPanel cardlayout_QuanLyDatMon;
    private javax.swing.JPanel cardlayout_QuanLyHoaDon;
    private javax.swing.JPanel cardlayout_QuanLyKhachHang;
    private javax.swing.JPanel cardlayout_QuanLyNhanVien;
    private javax.swing.JComboBox<String> cbo_qldb_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane scroll_menu;
    private javax.swing.JScrollPane scroll_qlban_bang;
    private javax.swing.JScrollPane scroll_qldb_bang;
    private javax.swing.JScrollPane scroll_qldm_bang;
    private javax.swing.JScrollPane scroll_qlhd_bang;
    private javax.swing.JScrollPane scroll_qlkh_bang;
    private javax.swing.JScrollPane scroll_qlnv_bang;
    private javax.swing.JTable table_menu;
    private javax.swing.JTable table_qlban_bang;
    private javax.swing.JTable table_qldb_bang;
    private javax.swing.JTable table_qldm_bang;
    private javax.swing.JTable table_qlhd_bang;
    private javax.swing.JTable table_qlkh_bang;
    private javax.swing.JTable table_qlnv_bang;
    private javax.swing.JPasswordField txt_dangnhap_matkhau;
    private javax.swing.JTextField txt_dangnhap_taikhoan;
    private javax.swing.JTextField txt_qlkh_makh;
    private javax.swing.JTextField txt_qlkh_sdt;
    private javax.swing.JTextField txt_qlkh_tenkh;
    private javax.swing.JTextField txt_qlkh_tim;
    private javax.swing.JTextField txt_qlnv_idtk;
    private javax.swing.JTextField txt_qlnv_mk;
    private javax.swing.JTextField txt_qlnv_sdt;
    private javax.swing.JTextField txt_qlnv_tennv;
    // End of variables declaration//GEN-END:variables
}
