/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UII;

import dao.*;
import java.awt.CardLayout;
import entity.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Outer = new javax.swing.JPanel();
        DangNhap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_dangnhap_taikhoan = new javax.swing.JTextField();
        btn_dangnhap_dangnhap = new javax.swing.JButton();
        txt_dangnhap_matkhau = new javax.swing.JPasswordField();
        ChucNang = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        cardlayout_QuanLyNhanVien = new javax.swing.JPanel();
        QuanLyNhanVien = new javax.swing.JPanel();
        btn_qlnv_suatknv = new javax.swing.JButton();
        btn_qlnv_dangkytknv = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_qlnv_tennv = new javax.swing.JTextField();
        txt_qlnv_manv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_qlnv_sdt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_qlnv_nhaplaimk = new javax.swing.JTextField();
        sp_qlnv = new javax.swing.JScrollPane();
        table_qlnv = new javax.swing.JTable();
        txt_qlnv_thongbao = new javax.swing.JTextField();
        txt_qlnv_matkhau = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cardlayout_QuanLyHoaDon = new javax.swing.JPanel();
        QuanLyHoaDon = new javax.swing.JPanel();
        btn_qlhd_thongke = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        ThongKe = new javax.swing.JPanel();
        btn_thongke_qlhd = new javax.swing.JButton();
        cardlayout_QuanLyKhachHang = new javax.swing.JPanel();
        QuanLyKhachHang = new javax.swing.JPanel();
        btn_qlkh_taokh = new javax.swing.JButton();
        btn_qlkh_suatt = new javax.swing.JButton();
        btn_qlkh_timkhtheosdt = new javax.swing.JButton();
        txt_qlkh_tim = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_qlkh_tenkh = new javax.swing.JTextField();
        txt_qlkh_sdt = new javax.swing.JTextField();
        txt_qlkh_makh = new javax.swing.JTextField();
        sp_qlkh = new javax.swing.JScrollPane();
        table_qlkh = new javax.swing.JTable();
        txt_qlkh_thongbao = new javax.swing.JTextField();
        txt_qlkh_thongbao1 = new javax.swing.JTextField();
        cardlayout_QuanLyBan = new javax.swing.JPanel();
        QuanLyBan = new javax.swing.JPanel();
        btn_qlban_trangchu = new javax.swing.JButton();
        btn_qlban_suaban = new javax.swing.JButton();
        btn_qlban_themban = new javax.swing.JButton();
        btn_qlban_xoaban = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cardlayout_QuanLyDatBan = new javax.swing.JPanel();
        cardlayout_QuanLyDatMon = new javax.swing.JPanel();
        QuanLyDatMon = new javax.swing.JPanel();
        btn_qldm_qldb = new javax.swing.JButton();
        btn_qldm_datmon = new javax.swing.JButton();
        btn_qldm_xoamon = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        DatMon = new javax.swing.JPanel();
        btn_datmon_qldm = new javax.swing.JButton();
        XoaMon = new javax.swing.JPanel();
        btn_xoamon_qldm = new javax.swing.JButton();
        SuaThongTinDatBan = new javax.swing.JPanel();
        btn_suattban_qldb = new javax.swing.JButton();
        DatBan = new javax.swing.JPanel();
        btn_db_qldb = new javax.swing.JButton();
        QuanLyDatBan = new javax.swing.JPanel();
        btn_qldb_trangchu = new javax.swing.JButton();
        btn_qldb_qldatmon = new javax.swing.JButton();
        btn_qldb_timkiem = new javax.swing.JButton();
        btn_qldb_laphoadon = new javax.swing.JButton();
        btn_qldb_suattdatban = new javax.swing.JButton();
        btn_qldb_huydatban = new javax.swing.JButton();
        btn_qldb_datban = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        Menu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_quanliban = new javax.swing.JButton();
        btn_quanlidb = new javax.swing.JButton();
        btn_quanlikh = new javax.swing.JButton();
        btn_quanlinv = new javax.swing.JButton();
        btn_quanlihd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setSize(new java.awt.Dimension(1100, 600));

        Outer.setBackground(new java.awt.Color(0, 255, 255));
        Outer.setMaximumSize(new java.awt.Dimension(1100, 600));
        Outer.setMinimumSize(new java.awt.Dimension(1100, 600));
        Outer.setName(""); // NOI18N
        Outer.setPreferredSize(new java.awt.Dimension(1100, 600));
        Outer.setLayout(new java.awt.CardLayout());

        DangNhap.setBackground(new java.awt.Color(255, 255, 255));
        DangNhap.setMaximumSize(new java.awt.Dimension(1100, 600));
        DangNhap.setMinimumSize(new java.awt.Dimension(1100, 600));
        DangNhap.setPreferredSize(new java.awt.Dimension(1100, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Tài Khoản :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mật Khẩu :");

        btn_dangnhap_dangnhap.setText("Đăng Nhập");
        btn_dangnhap_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhap_dangnhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DangNhapLayout = new javax.swing.GroupLayout(DangNhap);
        DangNhap.setLayout(DangNhapLayout);
        DangNhapLayout.setHorizontalGroup(
            DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapLayout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_dangnhap_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dangnhap_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangNhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangNhapLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangNhapLayout.createSequentialGroup()
                        .addComponent(btn_dangnhap_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        DangNhapLayout.setVerticalGroup(
            DangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangNhapLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_dangnhap_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dangnhap_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dangnhap_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Outer.add(DangNhap, "dangnhap");

        ChucNang.setBackground(new java.awt.Color(153, 255, 204));
        ChucNang.setMaximumSize(new java.awt.Dimension(1100, 600));
        ChucNang.setMinimumSize(new java.awt.Dimension(1100, 600));
        ChucNang.setPreferredSize(new java.awt.Dimension(1100, 600));
        ChucNang.setVerifyInputWhenFocusTarget(false);

        MainPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        MainPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        MainPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        MainPanel.setLayout(new java.awt.CardLayout());

        cardlayout_QuanLyNhanVien.setLayout(new java.awt.CardLayout());

        QuanLyNhanVien.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyNhanVien.setMinimumSize(new java.awt.Dimension(900, 600));
        QuanLyNhanVien.setPreferredSize(new java.awt.Dimension(900, 600));

        btn_qlnv_suatknv.setText("Sửa thông tin");
        btn_qlnv_suatknv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnv_suatknvActionPerformed(evt);
            }
        });

        btn_qlnv_dangkytknv.setText("Tạo Tài Khoản Nhân Viên");
        btn_qlnv_dangkytknv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnv_dangkytknvActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã Nhân Viên:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mật khẩu :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Số điện thoại:");

        table_qlnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhân viên", "Mã Tài Khoản", "Mật khẩu", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_qlnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_qlnvMouseClicked(evt);
            }
        });
        sp_qlnv.setViewportView(table_qlnv);
        if (table_qlnv.getColumnModel().getColumnCount() > 0) {
            table_qlnv.getColumnModel().getColumn(0).setResizable(false);
            table_qlnv.getColumnModel().getColumn(1).setResizable(false);
            table_qlnv.getColumnModel().getColumn(2).setResizable(false);
            table_qlnv.getColumnModel().getColumn(3).setResizable(false);
        }

        txt_qlnv_thongbao.setEditable(false);
        txt_qlnv_thongbao.setEnabled(false);
        txt_qlnv_thongbao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qlnv_thongbaoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Nhập lại mật khẩu:");

        javax.swing.GroupLayout QuanLyNhanVienLayout = new javax.swing.GroupLayout(QuanLyNhanVien);
        QuanLyNhanVien.setLayout(QuanLyNhanVienLayout);
        QuanLyNhanVienLayout.setHorizontalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                                .addComponent(txt_qlnv_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_qlnv_suatknv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_qlnv_dangkytknv))
                            .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                                        .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(39, 39, 39))
                                    .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_qlnv_tennv)
                                    .addComponent(txt_qlnv_nhaplaimk)
                                    .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                                        .addComponent(txt_qlnv_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txt_qlnv_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_qlnv_matkhau)))))
                    .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(sp_qlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        QuanLyNhanVienLayout.setVerticalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qlnv_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qlnv_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qlnv_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qlnv_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qlnv_nhaplaimk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_qlnv_suatknv)
                    .addComponent(txt_qlnv_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_qlnv_dangkytknv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(sp_qlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        cardlayout_QuanLyNhanVien.add(QuanLyNhanVien, "qlnv");

        MainPanel.add(cardlayout_QuanLyNhanVien, "qlynhanvien");

        cardlayout_QuanLyHoaDon.setLayout(new java.awt.CardLayout());

        QuanLyHoaDon.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyHoaDon.setMinimumSize(new java.awt.Dimension(900, 600));

        btn_qlhd_thongke.setText("Thống kê");
        btn_qlhd_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlhd_thongkeActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout QuanLyHoaDonLayout = new javax.swing.GroupLayout(QuanLyHoaDon);
        QuanLyHoaDon.setLayout(QuanLyHoaDonLayout);
        QuanLyHoaDonLayout.setHorizontalGroup(
            QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyHoaDonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_qlhd_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        QuanLyHoaDonLayout.setVerticalGroup(
            QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyHoaDonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_qlhd_thongke)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        cardlayout_QuanLyHoaDon.add(QuanLyHoaDon, "qlhd");

        btn_thongke_qlhd.setText("Quay Lại");
        btn_thongke_qlhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongke_qlhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_thongke_qlhd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_thongke_qlhd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyHoaDon.add(ThongKe, "thongke");

        MainPanel.add(cardlayout_QuanLyHoaDon, "qlyhoadon");

        cardlayout_QuanLyKhachHang.setLayout(new java.awt.CardLayout());

        QuanLyKhachHang.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyKhachHang.setMinimumSize(new java.awt.Dimension(900, 600));
        QuanLyKhachHang.setPreferredSize(new java.awt.Dimension(900, 600));

        btn_qlkh_taokh.setText("Tạo khách hàng");
        btn_qlkh_taokh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkh_taokhActionPerformed(evt);
            }
        });

        btn_qlkh_suatt.setText("Sửa thông tin");
        btn_qlkh_suatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkh_suattActionPerformed(evt);
            }
        });

        btn_qlkh_timkhtheosdt.setText("Tìm:");
        btn_qlkh_timkhtheosdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkh_timkhtheosdtActionPerformed(evt);
            }
        });

        txt_qlkh_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qlkh_timActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Tên khách hàng:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Số điện thoại:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Mã khách hàng:");

        table_qlkh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Mã khách hàng", "Số điện thoại"
            }
        ));
        // Giả sử bạn đã có một DefaultTableModel
        DefaultTableModel model = new DefaultTableModel();

        // Thêm cột vào model (nếu cần)
        model.addColumn("Tên Khách Hàng");
        model.addColumn("Mã Khách Hàng");
        model.addColumn("Số Điện Thoại");

        // Cài đặt model cho JTable
        table_qlkh.setModel(model);

        // Ngừng chỉnh sửa cho tất cả các ô trong bảng
        table_qlkh.setDefaultEditor(Object.class, null);  // Cách đơn giản ngừng chỉnh sửa
        table_qlkh.setCellSelectionEnabled(true);
        // Giả sử table_qlkh là tên của JTable chứa danh sách khách hàng.
        table_qlkh.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Kiểm tra nếu không có dòng nào được chọn
                if (!e.getValueIsAdjusting() && table_qlkh.getSelectedRow() != -1) {
                    // Lấy chỉ số của dòng được chọn
                    int selectedRow = table_qlkh.getSelectedRow();

                    // Lấy thông tin từ các cột trong dòng được chọn
                    String maKH = table_qlkh.getValueAt(selectedRow, 1).toString(); // Cột MaKH
                    String tenKH = table_qlkh.getValueAt(selectedRow, 0).toString(); // Cột TenKH
                    String soDienThoai = table_qlkh.getValueAt(selectedRow, 2).toString(); // Cột SoDienTHoai

                    // Điền thông tin vào các TextField
                    txt_qlkh_makh.setText(maKH);
                    txt_qlkh_tenkh.setText(tenKH);
                    txt_qlkh_sdt.setText(soDienThoai);
                }
            }
        });
        table_qlkh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_qlkh.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_qlkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_qlkhMouseClicked(evt);
            }
        });
        sp_qlkh.setViewportView(table_qlkh);

        txt_qlkh_thongbao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_qlkh_thongbao.setEnabled(false);
        txt_qlkh_thongbao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qlkh_thongbaoActionPerformed(evt);
            }
        });

        txt_qlkh_thongbao1.setEnabled(false);
        txt_qlkh_thongbao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qlkh_thongbao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyKhachHangLayout = new javax.swing.GroupLayout(QuanLyKhachHang);
        QuanLyKhachHang.setLayout(QuanLyKhachHangLayout);
        QuanLyKhachHangLayout.setHorizontalGroup(
            QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                                .addComponent(txt_qlkh_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_qlkh_suatt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_qlkh_taokh))
                            .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyKhachHangLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyKhachHangLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(4, 4, 4)))
                                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                                        .addComponent(txt_qlkh_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_qlkh_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_qlkh_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_qlkh_thongbao1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(txt_qlkh_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btn_qlkh_timkhtheosdt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QuanLyKhachHangLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(sp_qlkh, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        QuanLyKhachHangLayout.setVerticalGroup(
            QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyKhachHangLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_qlkh_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qlkh_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_qlkh_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_qlkh_suatt)
                    .addComponent(btn_qlkh_taokh)
                    .addComponent(txt_qlkh_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sp_qlkh, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(QuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_qlkh_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_qlkh_timkhtheosdt)
                    .addComponent(txt_qlkh_thongbao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        cardlayout_QuanLyKhachHang.add(QuanLyKhachHang, "qlkh");

        MainPanel.add(cardlayout_QuanLyKhachHang, "qlykhachhang");

        cardlayout_QuanLyBan.setLayout(new java.awt.CardLayout());

        QuanLyBan.setBackground(new java.awt.Color(204, 204, 204));

        btn_qlban_trangchu.setText("Trang Chủ");
        btn_qlban_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_trangchuActionPerformed(evt);
            }
        });

        btn_qlban_suaban.setText("Sửa bàn");
        btn_qlban_suaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_suabanActionPerformed(evt);
            }
        });

        btn_qlban_themban.setText("Thêm bàn");
        btn_qlban_themban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_thembanActionPerformed(evt);
            }
        });

        btn_qlban_xoaban.setText("Xóa bàn");
        btn_qlban_xoaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlban_xoabanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Bàn", "Mã Khu", "Trạng Thái", "Đơn Giá"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout QuanLyBanLayout = new javax.swing.GroupLayout(QuanLyBan);
        QuanLyBan.setLayout(QuanLyBanLayout);
        QuanLyBanLayout.setHorizontalGroup(
            QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_qlban_themban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlban_suaban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlban_trangchu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlban_xoaban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyBanLayout.setVerticalGroup(
            QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyBanLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyBanLayout.createSequentialGroup()
                        .addComponent(btn_qlban_trangchu)
                        .addGap(32, 32, 32)
                        .addComponent(btn_qlban_suaban)
                        .addGap(35, 35, 35)
                        .addComponent(btn_qlban_themban)
                        .addGap(33, 33, 33)
                        .addComponent(btn_qlban_xoaban))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyBan.add(QuanLyBan, "qlban");

        MainPanel.add(cardlayout_QuanLyBan, "qlyban");

        cardlayout_QuanLyDatBan.setLayout(new java.awt.CardLayout());

        cardlayout_QuanLyDatMon.setPreferredSize(new java.awt.Dimension(600, 400));
        cardlayout_QuanLyDatMon.setLayout(new java.awt.CardLayout());

        QuanLyDatMon.setMaximumSize(new java.awt.Dimension(900, 600));
        QuanLyDatMon.setMinimumSize(new java.awt.Dimension(900, 600));
        QuanLyDatMon.setPreferredSize(new java.awt.Dimension(900, 600));

        btn_qldm_qldb.setText("Quay Lại");
        btn_qldm_qldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldm_qldbActionPerformed(evt);
            }
        });

        btn_qldm_datmon.setText("Đặt món");
        btn_qldm_datmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldm_datmonActionPerformed(evt);
            }
        });

        btn_qldm_xoamon.setText("Xóa món");
        btn_qldm_xoamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldm_xoamonActionPerformed(evt);
            }
        });

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout QuanLyDatMonLayout = new javax.swing.GroupLayout(QuanLyDatMon);
        QuanLyDatMon.setLayout(QuanLyDatMonLayout);
        QuanLyDatMonLayout.setHorizontalGroup(
            QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_qldm_datmon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_qldm_xoamon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                        .addComponent(btn_qldm_qldb)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QuanLyDatMonLayout.setVerticalGroup(
            QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_qldm_qldb)
                .addGap(18, 18, 18)
                .addGroup(QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(QuanLyDatMonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(QuanLyDatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_qldm_datmon)
                            .addComponent(btn_qldm_xoamon)))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        cardlayout_QuanLyDatMon.add(QuanLyDatMon, "qldatmon");

        DatMon.setPreferredSize(new java.awt.Dimension(600, 400));

        btn_datmon_qldm.setText("Quay Lại");
        btn_datmon_qldm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datmon_qldmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatMonLayout = new javax.swing.GroupLayout(DatMon);
        DatMon.setLayout(DatMonLayout);
        DatMonLayout.setHorizontalGroup(
            DatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_datmon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatMonLayout.setVerticalGroup(
            DatMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_datmon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatMon.add(DatMon, "datmon");

        XoaMon.setPreferredSize(new java.awt.Dimension(600, 400));

        btn_xoamon_qldm.setText("Quay Lại");
        btn_xoamon_qldm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoamon_qldmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout XoaMonLayout = new javax.swing.GroupLayout(XoaMon);
        XoaMon.setLayout(XoaMonLayout);
        XoaMonLayout.setHorizontalGroup(
            XoaMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XoaMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_xoamon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        XoaMonLayout.setVerticalGroup(
            XoaMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XoaMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_xoamon_qldm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatMon.add(XoaMon, "xoamon");

        cardlayout_QuanLyDatBan.add(cardlayout_QuanLyDatMon, "qldm");

        btn_suattban_qldb.setText("Quay Lại");
        btn_suattban_qldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suattban_qldbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuaThongTinDatBanLayout = new javax.swing.GroupLayout(SuaThongTinDatBan);
        SuaThongTinDatBan.setLayout(SuaThongTinDatBanLayout);
        SuaThongTinDatBanLayout.setHorizontalGroup(
            SuaThongTinDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuaThongTinDatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_suattban_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SuaThongTinDatBanLayout.setVerticalGroup(
            SuaThongTinDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuaThongTinDatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_suattban_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatBan.add(SuaThongTinDatBan, "suattdatban");

        btn_db_qldb.setText("Quay Lại");
        btn_db_qldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_db_qldbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatBanLayout = new javax.swing.GroupLayout(DatBan);
        DatBan.setLayout(DatBanLayout);
        DatBanLayout.setHorizontalGroup(
            DatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_db_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatBanLayout.setVerticalGroup(
            DatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_db_qldb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatBan.add(DatBan, "datban");

        QuanLyDatBan.setPreferredSize(new java.awt.Dimension(1200, 900));

        btn_qldb_trangchu.setText("Trang Chủ");
        btn_qldb_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_trangchuActionPerformed(evt);
            }
        });

        btn_qldb_qldatmon.setText("Quản lý đặt món");
        btn_qldb_qldatmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_qldatmonActionPerformed(evt);
            }
        });

        btn_qldb_timkiem.setText("Tìm kiếm");
        btn_qldb_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_timkiemActionPerformed(evt);
            }
        });

        btn_qldb_laphoadon.setText("Lập hóa đơn");
        btn_qldb_laphoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_laphoadonActionPerformed(evt);
            }
        });

        btn_qldb_suattdatban.setText("Sửa thông tin đặt bàn");
        btn_qldb_suattdatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_suattdatbanActionPerformed(evt);
            }
        });

        btn_qldb_huydatban.setText("Hủy đặt bàn");
        btn_qldb_huydatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_huydatbanActionPerformed(evt);
            }
        });

        btn_qldb_datban.setText("Đặt bàn");
        btn_qldb_datban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldb_datbanActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyDatBanLayout = new javax.swing.GroupLayout(QuanLyDatBan);
        QuanLyDatBan.setLayout(QuanLyDatBanLayout);
        QuanLyDatBanLayout.setHorizontalGroup(
            QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_qldb_datban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_qldb_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_qldatmon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_laphoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_suattdatban, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_qldb_huydatban, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                        .addComponent(btn_qldb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyDatBanLayout.setVerticalGroup(
            QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_qldb_timkiem)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QuanLyDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyDatBanLayout.createSequentialGroup()
                        .addComponent(btn_qldb_trangchu)
                        .addGap(18, 18, 18)
                        .addComponent(btn_qldb_qldatmon)
                        .addGap(27, 27, 27)
                        .addComponent(btn_qldb_laphoadon)
                        .addGap(30, 30, 30)
                        .addComponent(btn_qldb_suattdatban)
                        .addGap(26, 26, 26)
                        .addComponent(btn_qldb_huydatban)
                        .addGap(28, 28, 28)
                        .addComponent(btn_qldb_datban))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardlayout_QuanLyDatBan.add(QuanLyDatBan, "qldb");

        MainPanel.add(cardlayout_QuanLyDatBan, "qlydatban");

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu.setDoubleBuffered(false);
        Menu.setMaximumSize(new java.awt.Dimension(200, 600));
        Menu.setMinimumSize(new java.awt.Dimension(200, 600));
        Menu.setName(""); // NOI18N
        Menu.setPreferredSize(new java.awt.Dimension(200, 600));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Menu Chức Năng");

        btn_quanliban.setText("Quản Lí Bàn");
        btn_quanliban.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_quanliban.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_quanliban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlibanActionPerformed(evt);
            }
        });

        btn_quanlidb.setText("Quản Lí Đặt Bàn");
        btn_quanlidb.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_quanlidb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlidbActionPerformed(evt);
            }
        });

        btn_quanlikh.setText("Quản Lí Khách Hàng");
        btn_quanlikh.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_quanlikh.setBorderPainted(false);
        btn_quanlikh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlikhActionPerformed(evt);
            }
        });

        btn_quanlinv.setText("Quản Lí Nhân Viên");
        btn_quanlinv.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_quanlinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlinvActionPerformed(evt);
            }
        });

        btn_quanlihd.setText("Quản Lí Hóa Đơn");
        btn_quanlihd.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_quanlihd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlihdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_quanlihd, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quanlinv, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quanlikh, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quanliban, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quanlidb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btn_quanliban, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlidb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlikh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlinv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanlihd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ChucNangLayout = new javax.swing.GroupLayout(ChucNang);
        ChucNang.setLayout(ChucNangLayout);
        ChucNangLayout.setHorizontalGroup(
            ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChucNangLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(900, Short.MAX_VALUE))
            .addGroup(ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChucNangLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        ChucNangLayout.setVerticalGroup(
            ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChucNangLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ChucNangLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        Outer.add(ChucNang, "chucnang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Outer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Outer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_qlnv_suatknvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnv_suatknvActionPerformed
        if(!checkinput_qlnv()){
            return;
        }
        String tennv = txt_qlnv_tennv.getText();
        String manv = txt_qlnv_manv.getText();
        String matkhau = txt_qlnv_matkhau.getText();
        String sdt = txt_qlnv_sdt.getText();
        NhanVien_DAO nv_dao = new NhanVien_DAO();
        TK_NhanVien_DAO tknv_dao = new TK_NhanVien_DAO();

        // Tạo đối tượng NhanVien và TK_NhanVien
        NhanVien nv = new NhanVien(manv, tennv, sdt);
        TK_NhanVien tknv = new TK_NhanVien(nv, matkhau);

        // Thêm nhân viên vào cơ sở dữ liệu
        if (!nv_dao.updateNhanVien(nv)) {
            txt_qlnv_thongbao.setText("Tải khoản này không có sẵn!");
            txt_qlnv_manv.requestFocus();
            return;
        }
        tknv_dao.updateTK_NhanVien(tknv);
        
        update_table_qlnv();
        JOptionPane.showMessageDialog(null, "Sửa thông tin thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_qlnv_suatknvActionPerformed

    private void btn_qlhd_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlhd_thongkeActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyHoaDon.getLayout();
        card.show(cardlayout_QuanLyHoaDon, "thongke");
    }//GEN-LAST:event_btn_qlhd_thongkeActionPerformed

    private void btn_thongke_qlhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongke_qlhdActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyHoaDon.getLayout();
        card.show(cardlayout_QuanLyHoaDon, "qlhd");
    }//GEN-LAST:event_btn_thongke_qlhdActionPerformed
    private void btn_qlkh_taokhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkh_taokhActionPerformed
        // TODO add your handling code here:
        if(!checkinput_qlkh()){
            return;
        }
        String tenkh = txt_qlkh_tenkh.getText();
        String makh = txt_qlkh_makh.getText();
        String sdt = txt_qlkh_sdt.getText();

        // Khởi tạo DAO
        KhachHang_DAO kh_dao = new KhachHang_DAO();

        // Tạo đối tượng NhanVien và TK_NhanVien
        KhachHang kh = new KhachHang(makh, tenkh, sdt);

        // Thêm nhân viên vào cơ sở dữ liệu
        if (!kh_dao.addKhachHang(kh)) {
            txt_qlkh_thongbao.setText("Đã có mã tài khoản này!");
            txt_qlkh_makh.requestFocus();
            return;
        }
        
        update_table_qlkh();
        JOptionPane.showMessageDialog(null, "Tạo thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_qlkh_taokhActionPerformed
    private boolean checkinput_qlkh() {
        String tenkh = txt_qlkh_tenkh.getText();
        String makh = txt_qlkh_makh.getText();
        String sdt = txt_qlkh_sdt.getText();

        if (tenkh == null || tenkh.trim().isEmpty()) {
            txt_qlkh_thongbao.setText("Tên khách hàng không được để trống!");
            txt_qlkh_tenkh.requestFocus();
            return false;
        }

        if (makh == null || makh.trim().isEmpty()) {
            txt_qlkh_thongbao.setText("Mã khách hàng không được để trống!");
            txt_qlkh_makh.requestFocus();
            return false;
        }

        if (sdt == null || sdt.trim().isEmpty()) {
            txt_qlkh_thongbao.setText("Số điện thoại không được để trống!");
            txt_qlkh_sdt.requestFocus();
            return false;
        }

        if (!sdt.matches("^(0\\d{9,10})$")) {
            txt_qlkh_thongbao.setText("Số điện thoại không hợp lệ!");
            txt_qlkh_sdt.requestFocus();
            return false;
        }

        if (!makh.matches("^KH\\d{3}$")) {
            txt_qlkh_thongbao.setText("Mã khách hàng phải theo mẫu KH000!");
            txt_qlkh_makh.requestFocus();
            return false;
        }

        // Nếu mọi điều kiện hợp lệ, trả về true
        return true;
    }

    private void btn_qlkh_suattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkh_suattActionPerformed
        if (!checkinput_qlkh()) {
            return;
        }

        String tenkh = txt_qlkh_tenkh.getText();
        String makh = txt_qlkh_makh.getText();
        String sdt = txt_qlkh_sdt.getText();
        KhachHang_DAO kh_dao = new KhachHang_DAO();

// Tạo đối tượng KhachHang
        KhachHang kh = new KhachHang(makh, tenkh, sdt);

// Cập nhật khách hàng vào cơ sở dữ liệu
        if (!kh_dao.updateKhachHang(kh)) {
            txt_qlkh_thongbao.setText("Mã khách hàng không tồn tại!");
            txt_qlkh_makh.requestFocus();
            return;
        }

// Cập nhật lại bảng dữ liệu khách hàng
        update_table_qlkh();
        JOptionPane.showMessageDialog(null, "Sửa thông tin khách hàng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_qlkh_suattActionPerformed

    private void btn_qlkh_timkhtheosdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkh_timkhtheosdtActionPerformed
        String sdt = txt_qlkh_tim.getText().trim();
        if (sdt.isEmpty()) {
            txt_qlkh_thongbao1.setText("Nhập số điện thoại cần tìm!");
            txt_qlkh_tim.requestFocus();
        }
        else if (!sdt.matches("^(0\\d{9,10})$")) {
            txt_qlkh_thongbao1.setText("Số điện thoại không hợp lệ!");
            txt_qlkh_tim.requestFocus();
        }
        else {
            // Tìm kiếm khách hàng theo số điện thoại
            KhachHang_DAO kh_dao = new KhachHang_DAO();
            List<KhachHang> khachHangs = kh_dao.searchKhachHangBySdt(sdt);
            txt_qlkh_thongbao1.setText(" ");
            // Cập nhật bảng với kết quả tìm kiếm
            update_table_qlkh_search(khachHangs);
        }
    }//GEN-LAST:event_btn_qlkh_timkhtheosdtActionPerformed
    private void update_table_qlkh_search(List<KhachHang> khachHangs) {
        DefaultTableModel model = (DefaultTableModel) table_qlkh.getModel();
        model.setRowCount(0);  // Xóa tất cả các dòng cũ

        if (khachHangs != null && !khachHangs.isEmpty()) {
            for (KhachHang kh : khachHangs) {
                model.addRow(new Object[]{kh.getTenKH(), kh.getMaKH(), kh.getSoDienTHoai()});
            }
        } else {
            txt_qlkh_thongbao1.setText("Không tìm thấy khách hàng với số điện thoại này.");
            txt_qlkh_tim.requestFocus();
        }
    }
    private void btn_qlban_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_trangchuActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "trangchu");
    }//GEN-LAST:event_btn_qlban_trangchuActionPerformed

    private void btn_qlban_suabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_suabanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyBan.getLayout();
        card.show(cardlayout_QuanLyBan, "suaban");
    }//GEN-LAST:event_btn_qlban_suabanActionPerformed

    private void btn_qlban_thembanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_thembanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyBan.getLayout();
        card.show(cardlayout_QuanLyBan, "themban");
    }//GEN-LAST:event_btn_qlban_thembanActionPerformed

    private void btn_qlban_xoabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlban_xoabanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyBan.getLayout();
        card.show(cardlayout_QuanLyBan, "xoaban");
    }//GEN-LAST:event_btn_qlban_xoabanActionPerformed

    private void btn_qldb_qldatmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_qldatmonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldm");
    }//GEN-LAST:event_btn_qldb_qldatmonActionPerformed

    private void btn_qldb_laphoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_laphoadonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "laphoadon");
    }//GEN-LAST:event_btn_qldb_laphoadonActionPerformed

    private void btn_qldb_suattdatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_suattdatbanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "suattdatban");
    }//GEN-LAST:event_btn_qldb_suattdatbanActionPerformed

    private void btn_qldb_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_trangchuActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "trangchu");
    }//GEN-LAST:event_btn_qldb_trangchuActionPerformed

    private void btn_qldb_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_timkiemActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "timkiem");
    }//GEN-LAST:event_btn_qldb_timkiemActionPerformed

    private void btn_qldb_huydatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_huydatbanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "huydatban");
    }//GEN-LAST:event_btn_qldb_huydatbanActionPerformed

    private void btn_qldb_datbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldb_datbanActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "datban");
    }//GEN-LAST:event_btn_qldb_datbanActionPerformed

    private void btn_qldm_qldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldm_qldbActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldb");
    }//GEN-LAST:event_btn_qldm_qldbActionPerformed

    private void btn_qldm_datmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldm_datmonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "datmon");
    }//GEN-LAST:event_btn_qldm_datmonActionPerformed

    private void btn_qldm_xoamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldm_xoamonActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "xoamon");
    }//GEN-LAST:event_btn_qldm_xoamonActionPerformed

    private void btn_datmon_qldmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datmon_qldmActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "qldatmon");
    }//GEN-LAST:event_btn_datmon_qldmActionPerformed

    private void btn_xoamon_qldmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoamon_qldmActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatMon.getLayout();
        card.show(cardlayout_QuanLyDatMon, "qldatmon");
    }//GEN-LAST:event_btn_xoamon_qldmActionPerformed

    private void btn_suattban_qldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suattban_qldbActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldb");
    }//GEN-LAST:event_btn_suattban_qldbActionPerformed

    private void btn_db_qldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_db_qldbActionPerformed
        CardLayout card = (CardLayout)cardlayout_QuanLyDatBan.getLayout();
        card.show(cardlayout_QuanLyDatBan, "qldb");
    }//GEN-LAST:event_btn_db_qldbActionPerformed

    private void btn_dangnhap_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhap_dangnhapActionPerformed
        // TODO add your handling code here:
        
        checkLoginCredentials();
    }//GEN-LAST:event_btn_dangnhap_dangnhapActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    private boolean checkinput_qlnv() {
        String tennv = txt_qlnv_tennv.getText();
        String manv = txt_qlnv_manv.getText();
        String matkhau = txt_qlnv_matkhau.getText();
        String nhaplai = txt_qlnv_nhaplaimk.getText();
        String sdt = txt_qlnv_sdt.getText();

        // Kiểm tra nếu các trường đầu vào rỗng
        if (tennv == null || tennv.trim().isEmpty()) {
            txt_qlnv_thongbao.setText("Tên nhân viên không được để trống!");
            txt_qlnv_tennv.requestFocus();
            return false;
        }

        if (manv == null || manv.trim().isEmpty()) {
            txt_qlnv_thongbao.setText("Mã nhân viên không được để trống!");
            txt_qlnv_manv.requestFocus();
            return false;
        }

        if (matkhau == null || matkhau.trim().isEmpty()) {
            txt_qlnv_thongbao.setText("Mật khẩu không được để trống!");
            txt_qlnv_matkhau.requestFocus();
            return false;
        }

        if (nhaplai == null || nhaplai.trim().isEmpty()) {
            txt_qlnv_thongbao.setText("Bạn cần nhập lại mật khẩu!");
            txt_qlnv_nhaplaimk.requestFocus();
            return false;
        }

        if (sdt == null || sdt.trim().isEmpty()) {
            txt_qlnv_thongbao.setText("Số điện thoại không được để trống!");
            txt_qlnv_sdt.requestFocus();
            return false;
        }

        // Kiểm tra xem mật khẩu và nhập lại mật khẩu có giống nhau không
        if (!matkhau.equals(nhaplai)) {
            txt_qlnv_thongbao.setText("Mật khẩu và nhập lại mật khẩu không khớp!");
            txt_qlnv_matkhau.requestFocus();
            return false;
        }

        // Kiểm tra định dạng số điện thoại (phải bắt đầu bằng số 0 và có 10 hoặc 11 chữ số)
        if (!sdt.matches("^(0\\d{9,10})$")) {
            txt_qlnv_thongbao.setText("Số điện thoại không hợp lệ!");
            txt_qlnv_sdt.requestFocus();
            return false;
        }

        // Kiểm tra định dạng mã nhân viên (bắt đầu bằng 'NV' và theo sau là 3 chữ số)
        if (!manv.matches("^NV\\d{3}$")) {
            txt_qlnv_thongbao.setText("Mã nhân viên phải theo mẫu NV000!");
            txt_qlnv_manv.requestFocus();
            return false;
        }

        // Nếu mọi điều kiện hợp lệ, trả về true
        return true;
    }
    private void btn_qlnv_dangkytknvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnv_dangkytknvActionPerformed
        // TODO add your handling code here:
        if(!checkinput_qlnv()){
            return;
        }
        String tennv = txt_qlnv_tennv.getText();
        String manv = txt_qlnv_manv.getText();
        String matkhau = txt_qlnv_matkhau.getText();
        String sdt = txt_qlnv_sdt.getText();

        // Khởi tạo DAO
        NhanVien_DAO nv_dao = new NhanVien_DAO();
        TK_NhanVien_DAO tknv_dao = new TK_NhanVien_DAO();

        // Tạo đối tượng NhanVien và TK_NhanVien
        NhanVien nv = new NhanVien(manv, tennv, sdt);
        TK_NhanVien tknv = new TK_NhanVien(nv, matkhau);

        // Thêm nhân viên vào cơ sở dữ liệu
        if (!nv_dao.addNhanVien(nv)) {
            txt_qlnv_thongbao.setText("Đã có mã tài khoản này!");
            txt_qlnv_manv.requestFocus();
            return;
        }
        tknv_dao.addTK_NhanVien(tknv);
        
        update_table_qlnv();
        JOptionPane.showMessageDialog(null, "Đăng ký thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_qlnv_dangkytknvActionPerformed
    private void update_table_qlnv(){
        DefaultTableModel model = (DefaultTableModel) table_qlnv.getModel();
        NhanVien_DAO nv_dao = new NhanVien_DAO();
        TK_NhanVien_DAO tknv_dao = new TK_NhanVien_DAO();
        ArrayList<NhanVien> nhanViens = (ArrayList<NhanVien>) nv_dao.getAllNhanViens();
        ArrayList<TK_NhanVien> taiKhoans = (ArrayList<TK_NhanVien>) tknv_dao.getAllTK_NhanViens();
        
        model.setRowCount(0);
        
        for (int i = 0; i < nhanViens.size(); i++) {            
            model.addRow(new Object[]{nhanViens.get(i).getTenNV(), nhanViens.get(i).getMaNV(), taiKhoans.get(i).getMatKhauTK(), nhanViens.get(i).getSoDienThoai()});
        }
        
    }
    private void btn_quanlidbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlidbActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "qlydatban");
    }//GEN-LAST:event_btn_quanlidbActionPerformed

    private void btn_quanlibanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlibanActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "qlyban");
    }//GEN-LAST:event_btn_quanlibanActionPerformed

    private void btn_quanlikhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlikhActionPerformed
        update_table_qlkh();
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "qlykhachhang");
    }//GEN-LAST:event_btn_quanlikhActionPerformed

    private void btn_quanlinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlinvActionPerformed
        // TODO add your handling code here:
        update_table_qlnv();
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "qlynhanvien");
    }//GEN-LAST:event_btn_quanlinvActionPerformed

    private void btn_quanlihdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlihdActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "qlyhoadon");
    }//GEN-LAST:event_btn_quanlihdActionPerformed

    private void txt_qlnv_thongbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qlnv_thongbaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qlnv_thongbaoActionPerformed

    private void table_qlnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_qlnvMouseClicked
        // TODO add your handling code here:
        int selectedRow = table_qlnv.getSelectedRow(); 
        
        if (selectedRow != -1) { 
            DefaultTableModel model = (DefaultTableModel) table_qlnv.getModel();

            String tennv = String.valueOf(model.getValueAt(selectedRow, 0)); 
            String manv = String.valueOf(model.getValueAt(selectedRow, 1)); 
            String matkhau = String.valueOf(model.getValueAt(selectedRow, 2)); 
            String sdt = String.valueOf(model.getValueAt(selectedRow, 3));
            

            txt_qlnv_tennv.setText(tennv);
            txt_qlnv_manv.setText(manv);
            txt_qlnv_sdt.setText(sdt);

            txt_qlnv_matkhau.setText(matkhau); 
            txt_qlnv_nhaplaimk.setText(matkhau); 
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để chỉnh sửa."); 
        }
    }//GEN-LAST:event_table_qlnvMouseClicked
    private void update_table_qlkh() {
    DefaultTableModel model = (DefaultTableModel) table_qlkh.getModel();
    KhachHang_DAO kh_dao = new KhachHang_DAO();
    ArrayList<KhachHang> khachHangs = (ArrayList<KhachHang>) kh_dao.getAllKhachHangs();

    // Kiểm tra nếu danh sách khách hàng không phải null và không rỗng
    if (khachHangs != null && !khachHangs.isEmpty()) {
        model.setRowCount(0); // Xóa tất cả các dòng cũ trong bảng

        for (KhachHang kh : khachHangs) {
            model.addRow(new Object[]{kh.getTenKH(), kh.getMaKH(), kh.getSoDienTHoai()});
        }
    } else {
        // Nếu danh sách khách hàng trống hoặc null, hiển thị thông báo cho người dùng
        model.setRowCount(0);
        JOptionPane.showMessageDialog(null, "Không có dữ liệu khách hàng!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
}

    private void txt_qlkh_thongbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qlkh_thongbaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qlkh_thongbaoActionPerformed

    private void txt_qlkh_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qlkh_timActionPerformed
            }//GEN-LAST:event_txt_qlkh_timActionPerformed

    private void txt_qlkh_thongbao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qlkh_thongbao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qlkh_thongbao1ActionPerformed

    private void table_qlkhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_qlkhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_qlkhMouseClicked
    
    /**
     * @param args the command line arguments
     */
    private void checkLoginCredentials() {
    String username = txt_dangnhap_taikhoan.getText().trim();
    String password = txt_dangnhap_matkhau.getText().trim();

    // Kiểm tra tài khoản có đúng định dạng không (6 số)
    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập tài khoản!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        txt_dangnhap_taikhoan.requestFocus();
        return;
    }

    // Kiểm tra mật khẩu không được để trống
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        txt_dangnhap_matkhau.requestFocus();
        return;
    }
    TK_NhanVien_DAO tknv_dao = new TK_NhanVien_DAO();
    List<TK_NhanVien> tknv_list = tknv_dao.getAllTK_NhanViens();
    boolean check = false;
    for(TK_NhanVien tknv : tknv_list){
        if(tknv.getNv().getMaNV().equals(username)&&tknv.getMatKhauTK().equals(password)){
            check = true;
            break;
        }
    }
    
    // Kiểm tra thông tin đăng nhập (thay bằng dữ liệu từ CSDL nếu cần)
    if (check) {
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        CardLayout card = (CardLayout)Outer.getLayout();
        card.show(Outer, "chucnang");
        // Mở giao diện trang chủ
        
    } else {
        JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChucNang;
    private javax.swing.JPanel DangNhap;
    private javax.swing.JPanel DatBan;
    private javax.swing.JPanel DatMon;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Outer;
    private javax.swing.JPanel QuanLyBan;
    private javax.swing.JPanel QuanLyDatBan;
    private javax.swing.JPanel QuanLyDatMon;
    private javax.swing.JPanel QuanLyHoaDon;
    private javax.swing.JPanel QuanLyKhachHang;
    private javax.swing.JPanel QuanLyNhanVien;
    private javax.swing.JPanel SuaThongTinDatBan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel XoaMon;
    private javax.swing.JButton btn_dangnhap_dangnhap;
    private javax.swing.JButton btn_datmon_qldm;
    private javax.swing.JButton btn_db_qldb;
    private javax.swing.JButton btn_qlban_suaban;
    private javax.swing.JButton btn_qlban_themban;
    private javax.swing.JButton btn_qlban_trangchu;
    private javax.swing.JButton btn_qlban_xoaban;
    private javax.swing.JButton btn_qldb_datban;
    private javax.swing.JButton btn_qldb_huydatban;
    private javax.swing.JButton btn_qldb_laphoadon;
    private javax.swing.JButton btn_qldb_qldatmon;
    private javax.swing.JButton btn_qldb_suattdatban;
    private javax.swing.JButton btn_qldb_timkiem;
    private javax.swing.JButton btn_qldb_trangchu;
    private javax.swing.JButton btn_qldm_datmon;
    private javax.swing.JButton btn_qldm_qldb;
    private javax.swing.JButton btn_qldm_xoamon;
    private javax.swing.JButton btn_qlhd_thongke;
    private javax.swing.JButton btn_qlkh_suatt;
    private javax.swing.JButton btn_qlkh_taokh;
    private javax.swing.JButton btn_qlkh_timkhtheosdt;
    private javax.swing.JButton btn_qlnv_dangkytknv;
    private javax.swing.JButton btn_qlnv_suatknv;
    private javax.swing.JButton btn_quanliban;
    private javax.swing.JButton btn_quanlidb;
    private javax.swing.JButton btn_quanlihd;
    private javax.swing.JButton btn_quanlikh;
    private javax.swing.JButton btn_quanlinv;
    private javax.swing.JButton btn_suattban_qldb;
    private javax.swing.JButton btn_thongke_qlhd;
    private javax.swing.JButton btn_xoamon_qldm;
    private javax.swing.JPanel cardlayout_QuanLyBan;
    private javax.swing.JPanel cardlayout_QuanLyDatBan;
    private javax.swing.JPanel cardlayout_QuanLyDatMon;
    private javax.swing.JPanel cardlayout_QuanLyHoaDon;
    private javax.swing.JPanel cardlayout_QuanLyKhachHang;
    private javax.swing.JPanel cardlayout_QuanLyNhanVien;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JScrollPane sp_qlkh;
    private javax.swing.JScrollPane sp_qlnv;
    private javax.swing.JTable table_qlkh;
    private javax.swing.JTable table_qlnv;
    private javax.swing.JPasswordField txt_dangnhap_matkhau;
    private javax.swing.JTextField txt_dangnhap_taikhoan;
    private javax.swing.JTextField txt_qlkh_makh;
    private javax.swing.JTextField txt_qlkh_sdt;
    private javax.swing.JTextField txt_qlkh_tenkh;
    private javax.swing.JTextField txt_qlkh_thongbao;
    private javax.swing.JTextField txt_qlkh_thongbao1;
    private javax.swing.JTextField txt_qlkh_tim;
    private javax.swing.JTextField txt_qlnv_manv;
    private javax.swing.JTextField txt_qlnv_matkhau;
    private javax.swing.JTextField txt_qlnv_nhaplaimk;
    private javax.swing.JTextField txt_qlnv_sdt;
    private javax.swing.JTextField txt_qlnv_tennv;
    private javax.swing.JTextField txt_qlnv_thongbao;
    // End of variables declaration//GEN-END:variables
}
